server.port=${SERVER_PORT:8084}
spring.application.name=report-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/report_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.datasource.hikari.initialization-fail-timeout=-1
spring.jpa.defer-datasource-initialization=true

algorithm.service.url=${ALGORITHM_SERVICE_URL:http://localhost:8083}
algorithm.service.similarity-path=/api/algorithm/similarity
algorithm.service.risk-path=/api/algorithm/risk
algorithm.service.patterns-path=/api/algorithm/patterns