# Config Server - Puerto por defecto 8888 (override: SERVER_PORT)
server.port=${SERVER_PORT:8888}

spring.application.name=config-server

# Activamos perfil native (sin Git)
spring.profiles.active=native

# Configuración del Config Server en modo local
spring.cloud.config.server.native.search-locations=classpath:/config-repo